spring:
  application:
    name: springboot-graphQL



  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  graphql:
    graphiql:
      enabled: true

  #  threads:
  #    virtual:
  #      enabled: true